In [3]:
import numpy as np

Создание массивов

In [34]:
a = np.array([1, 2, 3])
print(a)
print(type(a))
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [35]:
b = np.ones((2, 3, 4))
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [30]:
b = np.transpose(b) # b = np.ones((4, 3, 2))
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


Индексирование

In [38]:
m = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(m[1])
print(m[2, 1])

[4 5 6]
8


Вычисления

In [40]:
x = np.array([[1, 2],
             [3, 4]])
y = np.array([[5, 6],
             [7, 8]])
print(x+y)

[[ 6  8]
 [10 12]]
