In [1]:
import numpy as np

Создание массивов

In [2]:
a = np.array([1, 2, 3])
print(a)
print(type(a))
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [3]:
b = np.ones((2, 3, 4))
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [4]:
b = np.transpose(b) # b = np.ones((4, 3, 2))
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


Индексирование

In [5]:
m = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(m[1])
print(m[2, 1])

[4 5 6]
8


Вычисления

In [6]:
x = np.array([[1, 2],
             [3, 4]])
y = np.array([[5, 6],
             [7, 8]])
print(x+y)

[[ 6  8]
 [10 12]]


Вычисление простой статистики

In [10]:
data = np.array([2, 4, 6, 8, 10])

# Статистики
mean_val = np.mean(data) # среднее
sum_val = np.sum(data) # сумма
std_val = np.std(data) # стандартное отклонение
median_val = np.median(data) # медиана


print("Среднее (mean):",mean_val)
print("Сумма (sum):", sum_val)
print("Стандартное отклонение (std):", std_val)
print("Медиана (median):", median_val)

Среднее (mean): 6.0
Сумма (sum): 30
Стандартное отклонение (std): 2.8284271247461903
Медиана (median): 6.0
